spring:
  messages:
    basename: i18n/messages #配置国际化资源文件路径
    encoding: UTF-8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.240.193.177:3306/territory_person_dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: territory_person_dev
    password: territory_person_dev#test193
    hikari:
      auto-commit: false
      connection-timeout: 5000
      maximum-pool-size: 15
  application:
    name: hpcc-customer-manage
  cloud:
    nacos:
      discovery:
        #配置Nacos服务注册发现地址
        heart-beat-interval: 1000
        server-addr: 10.240.193.181:8848
        namespace: 15f006d8-d815-4251-878b-b65729cb4711
        group: LCDS_GROUP
        username: shjh
        password: shjh^&#$dev
        ephemeral: true
      config:
        #配置Nacos注册中心地址
        enabled: false
        server-addr: 10.240.193.181:8848
        username: shjh
        password: shjh^&#$dev
        file-extension: yaml
        namespace: 15f006d8-d815-4251-878b-b65729cb4711
        group: LCDS_GROUP
  servlet:
    multipart:
      # 根据实际需求作调整
      # 默认最大上传文件大小为10M，单个文件大小
      max-file-size: 50MB
      # 默认最大请求大小为15M，总上传的数据大小
      max-request-size: 100MB
      enabled: true
  #reids配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 10.240.193.176
    # Redis服务器连接端口
    port: 7001
    # Redis服务器连接密码（默认为空）
    password: hnhdrd@gientech.com
    timeout: 30000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# redis
redisson:
  single-server-config:
    address: 10.240.193.176:7001
    database: 0
    connection-pool-size: 4
    connection-minimum-idle-size: 1
    subscription-connection-pool-size: 4
  codec: com.gientech.lcds.data.auth.utils.JsonJacksonCodec
  password: hnhdrd@gientech.com

#logging:
#  level:
#    root: INFO
#    com.ejlchina.searcher.implement.DefaultSqlExecutor: DEBUG
#    com.uwdp.module.biz.infrastructure.mapper.LmcWorkflowMapper: DEBUG

#lcds
#lcds:
#  workflow:
#    # 获取表单服务 流程表单是零代码开发时需要配置,即流程的表单在前端开发平台上做的开发(通过拖拉拽的方式,且出码后不做页面调整)
#    form-server:
#      server-type: spring_cloud
#      service-id: baseService
#      server-addr: http://lcds-workflow
#    # 获取用户数据服务
#    uac-server:
#      server-type: spring_cloud
#      service-id: idaas-core-service
#      server-addr: http://uwdp-lcds-idaas-core-api.dc-uwdp:8087
#    # 工作流相关操作服务（例如提交流程等）
#    work-flow-server:
#      server-type: spring_cloud
#      service-id: lcds-workflow
#      server-addr: http://lcds-workflow
lcds:
  workflow:
    client-id: 7b01ef0233f3499ea3dcd57dc2071315
    open-api:
      #      传输密钥设置
      client-private-key: dd007742dd6aafa5edf9508e05c852e9e943070a99ca12fe09f6bffc9a85b4bc
        # 是否启用加密（根据该应用在流程引擎平台的配置）
        #encrypt: true
        # 是否启用签名（根据该应用在流程引擎平台的配置）
      #sign: true
      server-addr: http://uwdp-lcds-workflow-open-service-api.dc-uwdp-dev:8890/ # open服务地址
      # 工作流开放平台公钥（默认为： 035ba4be24a9d075b33b1c2ca40de228e94a7a6e539f112f9243710de74064b2bf）
      server-public-key: 035ba4be24a90075D3361C2Ca40de228e94a7a6e539f112F9243710de74064b2bf
common:
  user-info-url: https://idaas-api-dev.htpc.com.cn/open/1/sso/userinfo


# 关闭实体模型的权限校验
data-auth:
  enable: false

hpcc-mim-server:
  permisson-url: https://idaas-api-dev.htpc.com.cn/open/1/sso/permission/7b01ef0233f3499ea3dcd57dc2071315
  app-id: 1681853481029976065
  appId: 1681853481029976065
  tenantId: 1
  sysCode: MimMsg
  url: https://mim-dev.htpc.com.cn
  oaUrl: https://oa.htpc.com.cn/rest/ofs/ReceiveRequestInfoByJson


idaas:
  sdk:
#    server-address: https://uwdp-api-dev.htpc.com.cn/idaas-open-service
    tenant-id: 1642758
    client-id: 7b01ef0233f3499ea3dcd57dc2071315
    client-secret: 8fdd65f9fb1f4451b219aa8840461ece

################# 开启DEBUG日志 [begin] #################
feign:
  client:
    config:
      default:
        logger-level: FULL
logging:
  level:
    cn.zhxu.bs: DEBUG
################# 开启DEBUG日志 [end] ###################